openapi: 3.0.0
info:
  title: Repository Search API
  description: Interface for retrieving info from VCS. Current version support GitHub.
  version: 0.1.0
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /repositories/{ownerName}:
    get:
      summary: Returns a list of user's repository.
      description: Returns the list of repositories, that wasn't forked.
      parameters:
        - in: path
          name: ownerName
          schema:
            type: string
          required: true
          description: OwnerName of searched repositories
        - in: query
          name: pageable
          schema:
            $ref: Pageable
          required: false
          description: page, size, etc.
      responses:
        '200':
          description: A JSON array of repositories short info and latest branch.
          content:
            application/json:
              schema:
                $ref: PagedModel
        '400':
          description: Bad request. ownerName must exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '404':
          description: Any repository with ownerName not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '406':
          description: Only application/json media type allowed for Response Allow header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '5XX':
          description: Unexpected error. Some problems with connection.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
  /{repositoryName}/ownerName/{ownerName}:
    get:
      summary: Returns a list of user's repository.
      description: Returns the list of repositories, that wasn't forked.
      parameters:
        - in: path
          name: repositoryName
          schema:
            type: string
          required: true
          description: RepositoryName of searched repositories
        - in: path
          name: ownerName
          schema:
            type: string
          required: true
          description: OwnerName of searched repositories
      responses:
        '200':
          description: A JSON array of repositories short info and latest branch.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsRepository'
        '400':
          description: Bad request. ownerName must exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '404':
          description: Any repository with ownerName not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '406':
          description: Only application/json media type allowed for Response Allow header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '5XX':
          description: Unexpected error. Some problems with connection.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
  /{repositoryName}/ownerName/{ownerName}/branches:
    get:
      summary: Returns a list of user's repository.
      description: Returns the list of repositories, that wasn't forked.
      parameters:
        - in: path
          name: repositoryName
          schema:
            type: string
          required: true
          description: RepositoryName of searched repositories
        - in: path
          name: ownerName
          schema:
            type: string
          required: true
          description: OwnerName of searched repositories
      responses:
        '200':
          description: A JSON array of repositories short info and latest branch.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RsRepository'
        '400':
          description: Bad request. ownerName must exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '404':
          description: Any repository with ownerName not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '406':
          description: Only application/json media type allowed for Response Allow header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
        '5XX':
          description: Unexpected error. Some problems with connection.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RsErrorResponse'
components:
  schemas:
    RsRepository:
      type: object
      required:
        - name
        - ownerLogin
      properties:
        name:
          type: string
        ownerLogin:
          type: string
        branches:
          $ref: '#/components/schemas/RsBranch'
    RsBranch:
      type: object
      required:
        - name
        - lastCommitSha
      properties:
        name:
          type: string
        lastCommitSha:
          type: string
    RsErrorResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
        code:
          type: integer
        message:
          type: string
        data:
          type: object
